### PR TITLE
fix(rails): Log missing key warning after Rails initialization completes

### LINKED ISSUE #391: Difficulty configuring Bugsnag in Rails before it configures itself
Here's an example initializer in Rails:

``` ruby
# config/initializers/bugsnag.rb
puts "Bugsnag initializer reached"
Bugsnag.configure do |config|
  config.logger = Logger.new("/dev/null")
  config.api_key = ENV.fetch("BUGSNAG_API_KEY")
end
```

The Bugsnag ready message gets logged before this initializer runs:

```
$ rails c
** [Bugsnag] Bugsnag exception handler 5.5.0 ready
Bugsnag initializer reached
Loading development environment (Rails 5.1.4)
```

I want to change the Bugsnag logger and/or explicitly configure Bugsnag myself. I do not want the gem to try to automatically detect its own configuration. What is the correct way to do this in Rails and other Ruby environments when using Gemfiles/Rubygems to load this gem?

### PR DESCRIPTION
**Pull request by kattrali**
When not initializing using the `BUGSNAG_API_KEY` environment variable,
the first time the Railtie integration is loaded, no API key is 
available. At the bottom of the configure method, a warning is emitted
stating that no API key has been set, though this may not be true after
`config/initializers/bugsnag.rb` runs. This is the behavior being observed
in #391, causing concern that bugsnag is not working correctly when in
fact the log message is premature.

This change allows for `Bugsnag.configure` to be called without validating
the key, allowing the Railtie integration to add an additional check
once Rails initialization is complete.

Fixes #391

### CODE REVIEW

File: lib/bugsnag/integrations/railtie.rb [hunk 1]
```diff
@@ -69,6 +69,7 @@ class Railtie < Rails::Railtie
           end
         end
       end
+      Bugsnag.configure(true) # Validate API key is set
```
Comment (snmaynard) [inline lib/bugsnag/integrations/railtie.rb]: You dont even need this because the previous configure will also validate?

Comment (kattrali) [reply lib/bugsnag/integrations/railtie.rb]: There isn't another configure call if the generator was never run.

Comment (snmaynard) [reply lib/bugsnag/integrations/railtie.rb]: The one above I mean?

Comment (kattrali) [reply lib/bugsnag/integrations/railtie.rb]: Oh you mean the immediately preceding line? Yes, that would be more logical.

File: lib/bugsnag/integrations/railtie.rb [hunk 2]
```diff
@@ -36,7 +36,7 @@ class Railtie < Rails::Railtie
 
     config.before_initialize do
       # Configure bugsnag rails defaults
-      Bugsnag.configure do |config|
+      Bugsnag.configure(false) do |config|
```
Comment (snmaynard) [inline lib/bugsnag/integrations/railtie.rb]: get rid of the (false)?

File: spec/integrations/logger_spec.rb [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+    end
+
+    context 'skips setting an API key' do
+      it 'logs a warning' do
+        skip "Incompatible with Ruby <2.0 and JRuby" if incompatible
+        output = run_app('rails-no-config')
+        expect(output).to include(key_warning)
+      end
+    end
+  end
```
Comment (martin308) [inline spec/integrations/logger_spec.rb]: a test in here where the env variable is provided but is not a valid api key and `configure` is not called might be a good addition

File: lib/bugsnag.rb [hunk 4]
```diff
@@ -37,14 +37,10 @@ class << self
     # Configure the Bugsnag notifier application-wide settings.
     #
     # Yields a configuration object to use to set application settings.
-    def configure
+    def configure(validate_api_key=true)
```
[the remark this answers is not in the document]
Comment (kattrali) [reply lib/bugsnag.rb]: Supporting Ruby 1.9.3 makes this difficult as 2.0.0 introduced named parameters. It could potentially be something for the next major release.
